Sagaru/src/Sagaru/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Sagaru.Models;
using Microsoft.Data.Entity;
using Microsoft.AspNet.Identity;
using System.Security.Claims;

namespace Sagaru.Controllers
{
    public class AjaxController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        public AjaxController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            return View(_db.Projects.Where(x => x.User.Id == currentUser.Id));
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Project project)
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            project.User = currentUser;
            _db.Projects.Add(project);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Detail(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            ViewBag.Shape = await _db.Shapes.ToListAsync();
            return View(thisProject);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            return View(thisProject);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            _db.Projects.Remove(thisProject);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            return View(thisProject);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Project project)
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            project.User = currentUser;
            _db.Entry(project).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Sagaru/src/Sagaru/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Sagaru.Models;
using Microsoft.Data.Entity;
using Microsoft.AspNet.Identity;
using System.Security.Claims;

namespace Sagaru.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        public HomeController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            return View(_db.Projects.Where(x => x.User.Id == currentUser.Id));
        }
        //ajax calls
        public IActionResult AjaxCreate()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AjaxCreate(Project project)
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            project.User = currentUser;
            _db.Projects.Add(project);
            _db.SaveChanges();
            return Json(project);
            //return RedirectToAction("Index", "Account");
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Project project)
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            project.User = currentUser;
            _db.Projects.Add(project);
            _db.SaveChanges();
            return RedirectToAction("Index","Account");
        }
        public async Task<IActionResult> Detail(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            ViewBag.Shape = await _db.Shapes.ToListAsync();
            ViewBag.Flick = Flickr.GetFlickr();
            return View(thisProject);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            return View(thisProject);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            _db.Projects.Remove(thisProject);
            _db.SaveChanges();
            return RedirectToAction("Index","Account");
        }
        public async Task<IActionResult> Update(int id)
        {
            var thisProject = await _db.Projects.FirstOrDefaultAsync(projects => projects.ProjectId == id);
            return View(thisProject);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Project project)
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            project.User = currentUser;
            _db.Entry(project).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index","Account");
        }
        public IActionResult GetFlickr()
        {
            var allFlickr = Flickr.GetFlickr();
            return View(allFlickr);
        }
    }
}

Sagaru/src/Sagaru/Controllers/ShapeController.cs
using Sagaru.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.AspNet.Identity;
using System.Security.Claims;

namespace Sagaru.Controllers
{
    public class ShapeController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShapeController(UserManager<ApplicationUser> userManager, ApplicationDbContext db)
        {
            _userManager = userManager;
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            ViewBag.Project = await _db.Projects.Where(x => x.User.Id == currentUser.Id).ToListAsync();
            return View(await _db.Shapes.Where(x => x.User.Id == currentUser.Id).ToListAsync());
        }
        public async Task<IActionResult> Detail(int id)
        {
            ViewBag.Project = await _db.Projects.ToListAsync();
            var thisShape = await _db.Shapes.FirstOrDefaultAsync(shape => shape.ShapeId == id);
            return View(thisShape);
        }
        public async Task<IActionResult> Create()
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            ViewBag.ProjectId = new SelectList(_db.Projects.Where(x => x.User.Id == currentUser.Id), "ProjectId", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Shape shape)
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            shape.User = currentUser;
            _db.Shapes.Add(shape);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Update(int id)
        {
            var thisShape = await _db.Shapes.FirstOrDefaultAsync(shape => shape.ShapeId == id);
            ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "Name");
            return View(thisShape);
        }
        [HttpPost]
        public async Task<IActionResult >Update(Shape shape)
        {
            var currentUser = await _userManager.FindByIdAsync(User.GetUserId());
            shape.User = currentUser;
            _db.Entry(shape).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Delete(int id)
        {
            var thisShape = await _db.Shapes.FirstOrDefaultAsync(shape => shape.ShapeId == id);
            ViewBag.ProjectId = new SelectList(_db.Projects, "ProjectId", "Name");
            return View(thisShape);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var thisShape = await _db.Shapes.FirstOrDefaultAsync(shape => shape.ShapeId == id);
            _db.Shapes.Remove(thisShape);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Sagaru/src/Sagaru/Views/Home/AjaxCreate.cshtml
@model Sagaru.Models.Project

<h4>Add a new Project</h4>
<div class="form">
    @using (Html.BeginForm("AjaxCreate", "Home", FormMethod.Post, new { @class = "new-project" }))
    {
        <div class="row">
            <div class="col-sm-3">@Html.LabelFor(model => model.Name) @Html.TextBoxFor(model => model.Name) </div>
            <div class="col-sm-3">
                @Html.LabelFor(model => model.Description) @Html.TextBoxFor(model => model.Description)
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <input class="btn btn-warning" type="submit" value="Add new Project" />
            </div>
        </div>
    }
</div>
<script>
    $('.new-project').submit(function (event) {
        event.preventDefault();
        $.ajax({
            url: '@Url.Action("AjaxCreate")',
            type: 'POST',
            dataType: 'json',
            data: $(this).serialize(),
            success: function (result) {
                var resultMessage = '<li><a href="/Home/Detail/' + result.ProjectId + '">' + result.Name + '</a>  | <a href="/Home/Delete/' + result.ProjectId + '">Delete</a> | <a href="/Home/Update/' + result.ProjectId + '">Edit</a></li><ul><li>'+result.Description+'</li></ul>';
                $('#newProject').append(resultMessage);
            }
        });
    });
</script>

Sagaru/src/Sagaru/Views/Home/Create.cshtml
@{
    ViewData["Title"] = "Sagaru - Create a New Project";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Sagaru.Models.Project

<h2>Create</h2>
<hr />
<h4>Add a new Project</h4>
<div class="form">
    @using (Html.BeginForm())
    {
        <div class="row">
            <div class="col-sm-3">@Html.LabelFor(model => model.Name) @Html.TextBoxFor(model => model.Name) </div>
            <div class="col-sm-3">
                @Html.LabelFor(model => model.Description) @Html.TextBoxFor(model => model.Description)
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <input class="btn btn-warning" type="submit" value="Add new Project" />
            </div>
        </div>
     }
</div>

<p>@Html.ActionLink("Back to home", "Index", "Account")</p>

Sagaru/src/Sagaru/Views/Home/Delete.cshtml
@{
    ViewData["Title"] = "Project - Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Sagaru.Models.Project
<h2>Are you sure you want to delete this?</h2>
<hr />
@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
<p>@Html.ActionLink("Back to home", "Index", "Ajax")</p>

Sagaru/src/Sagaru/Views/Home/Detail.cshtml
@{
    ViewData["Title"] = "Item - Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@model Sagaru.Models.Project
<h2>Project Details</h2>
<hr />

<canvas id="myCanvas" width="500" height="500"></canvas>
<p>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</p>
<p>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</p>
<ul>
    @foreach (var listProject in Model.Shapes)
    {
         <li>@Html.DisplayFor(modelItem => listProject.Type)</li>
    }
</ul>
<p>@Html.ActionLink("Edit", "Update", "Home", new { id = Model.ProjectId }) | @Html.ActionLink("Back to Home", "Index", "Account")</p>
<div id="testy"></div>

@ViewBag.Flick

<script>
    const STATE_INIT = 10,
		STATE_PLAYING = 20;
    var Game = function() {
        this.canvas = document.getElementById('myCanvas');
        this.c = this.canvas.getContext('2d');
        this.gameObjects = [];
        this.flickrObjects = [];
        this.appState = STATE_INIT;
        this.mouseX = 0;
        this.mouseY = 0;
        this.isTheMouseBeingPressed = false;
        this.isTheMouseUnClicked = false;
        @foreach ( var flickr in ViewBag.Flick)
        {
            <text>
            var flickr = new Flickr("@flickr.Id", "@flickr.Title", "@flickr.Url_s", "@flickr.Url_l");
        this.flickrObjects.push(flickr);
            </text>
        }
        @foreach ( var shape in Model.Shapes)
        {
            <text>
            var shape = new Shape("@shape.Type", @shape.X, @shape.Y);
        this.gameObjects.push(shape);
            </text>
        }
        console.log(this.flickrObjects);
    };
    Game.prototype.mouseClicked  = function(event) {
        this.isTheMouseBeingPressed = true;
    }
    Game.prototype.mouseUnClicked  = function(event) {
        this.isTheMouseUnClicked = true;
    }
    Game.prototype.mouseMove = function(event) {
        if (event.offsetX || event.offsetX == 0) { // Opera
            this.mouseX = event.offsetX;
            this.mouseY = event.offsetY;
        } else if ( event.layerX ||  event.layerX == 0) { // Firefox
            console.log(event);
            this.mouseX = event.layerX;
            this.mouseY = event.layerY;
        }
    }
    Game.prototype.gameManager = function() {
        switch(this.appState){
            case STATE_INIT:
                this.canvas.addEventListener("mousedown", this.mouseClicked.bind(this), false);
                this.canvas.addEventListener("mouseup", this.mouseUnClicked.bind(this), false);
                this.canvas.addEventListener("mousemove", this.mouseMove.bind(this), false);
                this.appState = STATE_PLAYING;
                break;
            case STATE_PLAYING:
                this.c.fillStyle = "rgba(0,0,0,1)";
                this.c.fillRect(0,0,this.canvas.width,this.canvas.height);
                for(var i = 0; i < this.gameObjects.length;i++){
                    this.drawShape(this.gameObjects[i].type, this.gameObjects[i].x, this.gameObjects[i].y)
                }
                this.checkForNewShape();
                this.drawCursor();
                this.c.font = "30px monospace";
                this.c.fillStyle = "green";
                this.c.fillText("X: " + this.mouseX + " Y: " + this.mouseY, 10, 25)
                break;
        }
    };
    Game.prototype.checkForNewShape = function() {
        if (this.isTheMouseUnClicked === true) {
            var shape = new Shape("Circle", this.mouseX, this.mouseY);
            this.gameObjects.push(shape)
            this.isTheMouseUnClicked = false;
        }

    }
    Game.prototype.drawCursor = function() {
        this.c.fillStyle = "#D9D9D9";
        this.c.arc(this.mouseX, this.mouseY, 10, 0, Math.PI*2, true);
        this.c.closePath();
        this.c.fill();
    }
    Game.prototype.drawShape = function(shape, x, y) {
        switch(shape) {
            case "Triangle":
                this.c.fillStyle = "#D9D9D9";
                this.c.beginPath();
                this.c.moveTo(x, y);
                this.c.lineTo(x+10, y+10);
                this.c.lineTo(x-10, y+10);
                this.c.closePath();
                this.c.fill();
                break;
            case "Circle":
                this.c.fillStyle = "#D9D9D9";
                this.c.beginPath();
                this.c.arc(x, y, 10, 0, Math.PI*2, true);
                this.c.closePath();
                this.c.fill();
                break;
            case "Rectangle":
                this.c.fillStyle = "#D9D9D9";
                this.c.fillRect(x, y, 10, 10);
                break;
            default:
                //Draw Circle
                this.c.fillStyle = "#D9D9D9";
                this.c.arc(x, y, 10, 0, Math.PI*2, true);
                this.c.closePath();
                this.c.fill();
                break;
        }
    }
    Game.prototype.runTheGame = function() {
        var t = this;
        setInterval(function(){t.gameManager();}, 30);
    };
    var Shape = function(type, x, y) {
        this.type = type;
        this.x = x;
        this.y = y;
    };
    var Flickr = function(id, title, url_s, url_l) {
        this.id = id;
        this.title = title;
        this.url_s = url_s;
        this.url_l = url_l;    
    }
    function eventWindowLoaded() {
        var game = new Game();
        game.runTheGame();
    }
    (function () {
        window.addEventListener('load', eventWindowLoaded, false);
    }());
    $(window).load(function () {
        $.ajax({
            type: 'GET',
            dataType: 'html',
            url: '@Url.Action("GetFlickr","Home")',
            success: function (result) {
                $('#testy').html(result);
            }
        });
    });
</script>

Sagaru/src/Sagaru/Views/Home/GetFlickr.cshtml
@using System.Security.Claims

@model IEnumerable<Sagaru.Models.Flickr>

<h2>All Photos</h2>
<hr />
<ol>
    @foreach (var photo in Model)
    {
        <li>
            <ul>
                <li>Id: @Html.DisplayFor(modelItem => photo.Id)</li>
                <li>Title: @Html.DisplayFor(modelItem => photo.Title)</li>
                <li><img src="@Html.DisplayFor(modelItem => photo.Url_s)" /></li>
                <li>LargeUrl: @Html.DisplayFor(modelItem => photo.Url_l)</li>
            </ul>
        </li>
    }
</ol>

Sagaru/src/Sagaru/Views/Home/Index.cshtml
@using System.Security.Claims

@model IEnumerable<Sagaru.Models.Project>

<h2>List of Projects:</h2>
<hr />

<ul id="newProject">
    @foreach (var listProject in Model)
    {
        <li>@Html.ActionLink(listProject.Name, "Detail", "Home", new { id = listProject.ProjectId })  | @Html.ActionLink("Delete", "Delete", "Home", new { id = listProject.ProjectId }) | @Html.ActionLink("Edit", "Update","Home", new { id = listProject.ProjectId })</li>
        <ul>
            <li>@Html.DisplayFor(modelItem => listProject.Description)</li>
        </ul>
    }
</ul>

<p>@Html.ActionLink("Add new Project", "Create", "Home")</p>
<p>@Html.ActionLink("View and Add Shapes", "Index", "Shape")</p>

Sagaru/src/Sagaru/Views/Home/Update.cshtml
@{
    ViewData["Title"] = "Item - Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Sagaru.Models.Project
<h2>Edit</h2>
<hr />
<h4>Edit this item: @Html.DisplayFor(model => model.Name)</h4>
<div class="form">
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.ProjectId)
        @Html.HiddenFor(model => model.FlickerImageLarge)
        @Html.HiddenFor(model => model.FlickerImageSmall)
        <div class="row">
            <div class="col-sm-3">@Html.LabelFor(model => model.Name) @Html.TextBoxFor(model => model.Name) </div>
            <div class="col-sm-3">
                @Html.LabelFor(model => model.Description) @Html.TextBoxFor(model => model.Description)
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <input class="btn btn-warning" type="submit" value="Save" />
            </div>
        </div>
    }
</div>
@Html.ActionLink("Back to Home", "Index", "Account")